name: Cake

on:
  push:
    branches: [ reactor ]
  pull_request:
    branches: [ reactor ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Cake Action
        uses: cake-build/cake-action@v1.2.0
