name: Cake

on:
  push:
    branches: [ reactor ]
  pull_request:
    branches: [ reactor ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.101

      - name: Cake Action
        uses: cake-build/cake-action@v1.2.0
        arguments: |
          isBleedingEdge: true
          buildId: $GITHUB_RUN_NUMBER

      - uses: actions/upload-artifact@v2
        with:
          name: BepInEx-reactor
          path: bin/dist/BepInEx_UnityIL2CPP_x86*.zip
